# Generated by Django 3.1.3 on 2020-12-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Players', '0005_auto_20201222_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('weather', models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold'), ('humid', 'Humid'), ('windy', 'Windy'), ('dew', 'Dew')], default='hot', max_length=10)),
                ('pitch', models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('dusty', 'Dusty'), ('flat', 'Flat'), ('green', 'Sprinkle of grass'), ('moist', 'Moist')], default='hard', max_length=30)),
                ('field', models.CharField(choices=[('moregrass', 'More Grass'), ('lessgrass', 'Less Grass'), ('large out field', 'Large Out Field'), ('small out field', 'Small Out Field'), ('soft', 'Soft Ground'), ('moist', 'Moist Ground')], default='moregrass', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('captain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captain', to='Players.player')),
                ('homeground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeground', to='Teams.stadium')),
                ('players', models.ManyToManyField(null=True, related_name='players', to='Players.Player')),
                ('wicketkeeper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wicketkeeper', to='Players.player')),
            ],
        ),
    ]
