# Generated by Django 3.1.3 on 2020-12-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bugdet',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='team',
            name='coin',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
