# Generated by Django 3.1.3 on 2020-12-27 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20201225_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coin',
        ),
        migrations.AlterField(
            model_name='stadium',
            name='field',
            field=models.CharField(choices=[('moregrass', 'More Grass'), ('lessgrass', 'Less Grass'), ('large out field', 'Large Out Field'), ('small out field', 'Small Out Field'), ('soft', 'Soft Ground'), ('moist', 'Moist Ground'), ('uneven', 'Uneven'), ('cracked', 'Cracked')], default='moregrass', max_length=30),
        ),
    ]
