# Generated by Django 3.1.3 on 2020-12-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0003_auto_20201227_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='field',
            field=models.CharField(choices=[('moregrass', 'More Grass'), ('lessgrass', 'Less Grass'), ('large out field', 'Large Out Field'), ('small out field', 'Small Out Field'), ('soft', 'Soft Ground'), ('moist', 'Moist Ground')], default='moregrass', max_length=30),
        ),
        migrations.AlterField(
            model_name='stadium',
            name='pitch',
            field=models.CharField(choices=[('hard', 'Hard'), ('soft', 'Soft'), ('dusty', 'Dusty'), ('flat', 'Flat'), ('green', 'Sprinkle of grass'), ('moist', 'Moist'), ('uneven', 'Uneven'), ('cracked', 'Cracked')], default='hard', max_length=30),
        ),
    ]
