# Generated by Django 3.1.3 on 2020-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0004_auto_20201227_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='average',
            field=models.IntegerField(default=160),
        ),
    ]
