# Generated by Django 3.1.3 on 2021-01-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0005_stadium_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='field',
            field=models.CharField(choices=[('moregrass', 'More Grass'), ('lessgrass', 'Less Grass'), ('largeoutfield', 'Large Out Field'), ('smalloutfield', 'Small Out Field'), ('soft', 'Soft Ground'), ('moist', 'Moist Ground')], default='moregrass', max_length=30),
        ),
    ]
