# Generated by Django 3.1.3 on 2021-01-06 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0006_auto_20210103_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='homeground',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeground', to='Teams.stadium'),
        ),
    ]
