# Generated by Django 3.1.3 on 2021-01-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0007_auto_20210107_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner_name',
            field=models.CharField(default='geetansh', max_length=100),
        ),
    ]
