# Generated by Django 3.1.3 on 2021-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0008_team_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='battingLineup',
            field=models.CharField(default='NOT SET', max_length=200),
        ),
    ]
