# Generated by Django 3.1.3 on 2021-01-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0009_team_battinglineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='battingLineup',
            field=models.TextField(default='NOT SET', max_length=200),
        ),
    ]
