# Generated by Django 3.1.3 on 2021-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0010_auto_20210129_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bowlingLineup',
            field=models.TextField(default='NOT SET', max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='lineup_flag',
            field=models.BooleanField(default=False),
        ),
    ]
