# Generated by Django 3.1.3 on 2021-02-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0011_auto_20210130_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='battingLineup',
            field=models.TextField(default='NOT SET', max_length=400),
        ),
        migrations.AlterField(
            model_name='team',
            name='bowlingLineup',
            field=models.TextField(default='NOT SET', max_length=400),
        ),
    ]
