# Generated by Django 3.1.3 on 2020-12-22 13:48

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.RegexValidator('[1-5]{1}[0-9]{1}', 'Age of the player must be in the range of 10-59.', 'Age of the player must be in the range of 10-59.')])),
                ('image', models.ImageField(height_field='250', upload_to='Players/', width_field='250')),
                ('playertype', models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'All-Rounder'), ('wicketkeeperbatsman', 'Wicket-Keeper Batsman')], default='batsman', max_length=25)),
                ('battinghand', models.CharField(choices=[('right', 'Right Hand Batsman'), ('left', 'Left Hand Batsman')], default='right', max_length=20)),
                ('bowlingtype', models.CharField(choices=[('None', 'None'), ('right arm fast', 'Right Arm Fast'), ('left arm fast', 'left Arm Fast'), ('right arm seam', 'Right Arm Seam'), ('left arm seam', 'Left Arm Seam'), ('right arm off spin', 'Right Arm Off Spin'), ('left arm off spin', 'Left Arm Off Spin'), ('right arm leg spin', 'Right Arm Leg Spin'), ('left arm leg spin', 'Left Arm Leg Spin')], default='None', max_length=50)),
                ('experience', models.IntegerField(validators=[django.core.validators.RegexValidator('\x08([0-9]|[1-9][0-9]|100)\x08', 'Value for Experience must be in the range of 0 to 100.', 'Value for Experience must be in the range of 0 to 100.')])),
                ('batskill', models.IntegerField(validators=[django.core.validators.RegexValidator('\x08([0-9]|[1-9][0-9]|100)\x08', 'Value for Bat-Skill must be in the range of 0 to 100.', 'Value for Bat-Skill must be in the range of 0 to 100.')])),
                ('bowlskill', models.IntegerField(validators=[django.core.validators.RegexValidator('\x08([0-9]|[1-9][0-9]|100)\x08', 'Value for Bowl-Skill must be in the range of 0 to 100.', 'Value for Bowl-Skill must be in the range of 0 to 100.')])),
                ('wktskill', models.IntegerField(validators=[django.core.validators.RegexValidator('\x08([0-9]|[1-9][0-9]|100)\x08', 'Value for WicketKeeping-Skill must be in the range of 0 to 100.', 'Value for WicketKeeping-Skill must be in the range of 0 to 100.')])),
                ('battingorder', models.CharField(default='[50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]', max_length=100)),
                ('bowlingorder', multiselectfield.db.fields.MultiSelectField(choices=[('powerplay', 'Power-Play'), ('midover', 'Mid-Overs'), ('deathover', 'Death-Bowler')], max_length=27)),
                ('batcomfort', multiselectfield.db.fields.MultiSelectField(choices=[('fast', 'Fast'), ('seam', 'Seam'), ('spin', 'Spin'), ('right', 'Right-Hand-Bowler'), ('left', 'Left-Hand-Bowler')], max_length=25)),
                ('bowlcomfort', multiselectfield.db.fields.MultiSelectField(choices=[('right', 'Right-Hand-Batsman'), ('left', 'Left-Hand-Batsman')], max_length=10)),
            ],
        ),
    ]
