# Generated by Django 3.1.3 on 2020-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bowlingtype',
            field=models.CharField(choices=[('None', 'None'), ('right arm fast', 'Right Arm Fast'), ('left arm fast', 'Left Arm Fast'), ('right arm seam', 'Right Arm Seam'), ('left arm seam', 'Left Arm Seam'), ('right arm off spin', 'Right Arm Off Spin'), ('left arm off spin', 'Left Arm Off Spin'), ('right arm leg spin', 'Right Arm Leg Spin'), ('left arm leg spin', 'Left Arm Leg Spin')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(height_field='250', null=True, upload_to='Players/', width_field='250'),
        ),
    ]
