# Generated by Django 3.1.3 on 2020-12-22 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0002_auto_20201222_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='batskill',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^([0-9]|[1-9][0-9]|100)$', 'Value for Bat-Skill must be in the range of 0 to 100.', 'Value for Bat-Skill must be in the range of 0 to 100.')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='bowlskill',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^([0-9]|[1-9][0-9]|100)$', 'Value for Bowl-Skill must be in the range of 0 to 100.', 'Value for Bowl-Skill must be in the range of 0 to 100.')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='experience',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^([0-9]|[1-9][0-9]|100)$', 'Value for Experience must be in the range of 0 to 100.', 'Value for Experience must be in the range of 0 to 100.')]),
        ),
        migrations.AlterField(
            model_name='player',
            name='wktskill',
            field=models.IntegerField(validators=[django.core.validators.RegexValidator('^([0-9]|[1-9][0-9]|100)$', 'Value for WicketKeeping-Skill must be in the range of 0 to 100.', 'Value for WicketKeeping-Skill must be in the range of 0 to 100.')]),
        ),
    ]
