# Generated by Django 3.1.3 on 2020-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0003_auto_20201222_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='Players/'),
        ),
    ]
