# Generated by Django 3.1.3 on 2020-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0004_auto_20201222_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='image',
            field=models.ImageField(default='Players/default.png', upload_to='Players/'),
        ),
    ]
